### ISSUE TITLE
cws

### ISSUE THREAD

**Issue by qerqa** [kinnerapriyap/ketu-the-img#2]
<img src="https://user-images.githubusercontent.com/116244131/198950047-d32fc293-5f94-436c-ad04-5d58b948f672.jpg" width=300 />

**Comment by qerqa** [comment]
<img src="https://user-images.githubusercontent.com/116244131/198950345-d34b5a88-775e-41dc-9c8c-6180cc6075c4.jpg" width=600 />

**Comment by kinnerapriyap** [comment]
Please reopen with a description and issue reproduction steps
